# Generated by Django 4.1.3 on 2022-11-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=290)),
                ('client_code', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=290)),
                ('surname', models.CharField(max_length=290)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.ManyToManyField(blank=True, null=True, related_name='contacts', to='clientList.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientlink', models.ManyToManyField(blank=True, null=True, related_name='clientlink', to='clientList.client')),
                ('contactlink', models.ManyToManyField(blank=True, null=True, related_name='contactlink', to='clientList.contact')),
            ],
        ),
    ]
