# Generated by Django 4.1.3 on 2022-11-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientlink', models.ManyToManyField(blank=True, null=True, related_name='contacts', to='clientList.contact')),
                ('contactlink', models.ManyToManyField(blank=True, null=True, related_name='clients', to='clientList.client')),
            ],
        ),
    ]
