# Generated by Django 4.1.2 on 2022-10-31 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='no',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=290),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientList.client'),
        ),
    ]
